"""add password_updated_at to user

Revision ID: f23beb7a194a
Revises: 9090576bb485
Create Date: 2025-01-09 14:57:30.745938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f23beb7a194a'
down_revision: Union[str, None] = '9090576bb485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_updated_at')
    # ### end Alembic commands ###
